const commons = @import("./commons.zig");
const StructDefinition = commons.StructDefinition;
const Method = commons.Method;
const MethodParam = commons.MethodParam;
const windows = @import("windows.schema.zig");

pub const required_imports = &.{
    .{ .alias = "std", .path = "@import(\"std\")" },
    .{ .alias = "winapi", .path = "std.builtin.CallingConvention.winapi" },
    .{ .alias = "windows", .path = "std.os.windows" },
    .{ .alias = "GUID", .path = "windows.GUID" },
    .{ .alias = "ULONG", .path = "windows.ULONG" },
    .{ .alias = "UINT", .path = "windows.UINT" },
    .{ .alias = "LPCWSTR", .path = "windows.LPCWSTR" },
    .{ .alias = "HRESULT", .path = "windows.HRESULT" },
    .{ .alias = "win_gen", .path = "@import(\"windows.generated.zig\")" },
    .{ .alias = "IUnknown", .path = "win_gen.IUnknown" },
};

pub const Interfaces = .{
    .IObject = StructDefinition{
        .base = "windows.IUnknown",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "GetPrivateData",
                .call_conv = "winapi",
                .namespace = null,
                .return_type = "HRESULT",
                .method_type = .Default,
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "guid", .member_type = "*const GUID" },
                    .{ .name = "data_size", .member_type = "*UINT" },
                    .{ .name = "data", .member_type = "?*anyopaque" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12object-getprivatedata",
            },
            .{
                .name = "SetPrivateData",
                .call_conv = "winapi",
                .namespace = null,
                .return_type = "HRESULT",
                .method_type = .Default,
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "guid", .member_type = "*const GUID" },
                    .{ .name = "data_size", .member_type = "UINT" },
                    .{ .name = "data", .member_type = "?*const anyopaque" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12object-setprivatedata",
            },
            .{
                .name = "SetPrivateDataInterface",
                .call_conv = "winapi",
                .namespace = null,
                .return_type = "HRESULT",
                .method_type = .Default,
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "guid", .member_type = "*const GUID" },
                    .{ .name = "data", .member_type = "?*const IUnknown" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12object-setprivatedatainterface",
            },
            .{
                .name = "SetName",
                .call_conv = "winapi",
                .namespace = null,
                .return_type = "HRESULT",
                .method_type = .Default,
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "name", .member_type = "LPCWSTR" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12object-setname",
            },
        },
    },
    .IDeviceChild = StructDefinition{
        .base = "dx12.IObject",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "GetDevice",
                .call_conv = "winapi",
                .namespace = null,
                .return_type = "HRESULT",
                .method_type = .Default,
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "guid", .member_type = "*const GUID" },
                    .{ .name = "device", .member_type = "*?*anyopaque" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12devicechild-getdevice",
            },
        },
    },
    .IPageable = StructDefinition{
        .base = "dx12.IDeviceChild",
        .is_extern = true,
        .methods = &.{},
    },
    .IRootSignature = StructDefinition{
        .base = "dx12.IDeviceChild",
        .is_extern = true,
        .methods = &.{},
    },
    .IQueryHeap = StructDefinition{
        .base = "dx12.IPageable",
        .is_extern = true,
        .methods = &.{},
    },
    .ICommandSignature = StructDefinition{
        .base = "dx12.IPageable",
        .is_extern = true,
        .methods = &.{},
    },
    .IHeap = StructDefinition{
        .base = "dx12.IPageable",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "GetDesc",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .ParamReturn,
                .return_type = "HEAP_DESC",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "HEAP_DESC", .member_type = "HEAP_DESC" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12heap-getdesc",
            },
        },
    },
    .IResource = StructDefinition{
        .base = "dx12.IPageable",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "Map",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "subresource", .member_type = "UINT" },
                    .{ .name = "read_range", .member_type = "?*const RANGE" },
                    .{ .name = "data", .member_type = "*?*anyopaque" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource-map",
            },
            .{
                .name = "Unmap",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "subresource", .member_type = "UINT" },
                    .{ .name = "written_range", .member_type = "?*const RANGE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource-unmap",
            },
            .{
                .name = "GetDesc",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .ParamReturn,
                .return_type = "RESOURCE_DESC",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "desc", .member_type = "RESOURCE_DESC" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource-getdesc",
            },
            .{
                .name = "GetGPUVirtualAddress",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "GPU_VIRTUAL_ADDRESS",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource-getgpuvirtualaddress",
            },
            .{
                .name = "WriteToSubresource",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst_subresource", .member_type = "UINT" },
                    .{ .name = "dst_box", .member_type = "?*const BOX" },
                    .{ .name = "src_data", .member_type = "*const anyopaque" },
                    .{ .name = "src_row_pitch", .member_type = "UINT" },
                    .{ .name = "src_depth_pitch", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource-writetosubresource",
            },
            .{
                .name = "ReadFromSubresource",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst_data", .member_type = "*anyopaque" },
                    .{ .name = "dst_row_pitch", .member_type = "UINT" },
                    .{ .name = "dst_depth_pitch", .member_type = "UINT" },
                    .{ .name = "src_subresource", .member_type = "UINT" },
                    .{ .name = "src_box", .member_type = "?*const BOX" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource-readfromsubresource",
            },
            .{
                .name = "GetHeapProperties",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "properties", .member_type = "?*HEAP_PROPERTIES" },
                    .{ .name = "flags", .member_type = "?*HEAP_FLAGS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource-getheapproperties",
            },
        },
    },
    .IResource1 = StructDefinition{
        .base = "dx12.IResource",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "GetProtectedResourceSession",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "guid", .member_type = "*const GUID" },
                    .{ .name = "session", .member_type = "*?*anyopaque" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12resource1-getprotectedresourcesession",
            },
        },
    },
    .ICommandAllocator = StructDefinition{
        .base = "dx12.IPageable",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "Reset",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandallocator-reset",
            },
        },
    },
    .IFence = StructDefinition{
        .base = "dx12.IPageable",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "GetCompletedValue",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "UINT64",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12fence-getcompletedvalue",
            },
            .{
                .name = "SetEventOnCompletion",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "value", .member_type = "UINT64" },
                    .{ .name = "event", .member_type = "HANDLE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12fence-seteventoncompletion",
            },
            .{
                .name = "Signal",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "value", .member_type = "UINT64" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12fence-signal",
            },
        },
    },
    .IFence1 = StructDefinition{
        .base = "dx12.IFence",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "GetCreationFlags",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "FENCE_FLAGS",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12fence1-getcreationflags",
            },
        },
    },
    .IPipelineState = StructDefinition{
        .base = "dx12.IPageable",
        .is_extern = true,
        .methods = &.{.{
            .name = "GetCachedBlob",
            .call_conv = "winapi",
            .namespace = null,
            .method_type = .Default,
            .return_type = "HRESULT",
            .params = &.{
                .{ .name = "self", .member_type = "*@This()" },
                .{ .name = "blob", .member_type = "d3d.IBlob" },
            },
            .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12pipelinestate-getcachedblob",
        }},
    },
    .IDesciptorHeap = StructDefinition{
        .base = "dx12.IPageable",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "GetDesc",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .ParamReturn,
                .return_type = "DESCRIPTOR_HEAP_DESC",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "desc", .member_type = "DESCRIPTOR_HEAP_DESC" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12descriptorheap-getdesc",
            },
            .{
                .name = "GetCPUDescriptorHandleForHeapStart",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .ParamReturn,
                .return_type = "CPU_DESCRIPTOR_HANDLE",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "desc", .member_type = "CPU_DESCRIPTOR_HANDLE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12descriptorheap-getcpudescriptorhandleforheapstart",
            },
            .{
                .name = "GetGPUDescriptorHandleForHeapStart",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .ParamReturn,
                .return_type = "GPU_DESCRIPTOR_HANDLE",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "desc", .member_type = "GPU_DESCRIPTOR_HANDLE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12descriptorheap-getcpudescriptorhandleforheapstart",
            },
        },
    },
    .ICommandList = StructDefinition{
        .base = "dx12.IDeviceChild",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "GetType",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "COMMAND_LIST_TYPE",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12devicechild-getdevice",
            },
        },
    },
    .IGraphicsCommandList = StructDefinition{
        .base = "dx12.ICommandList",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "Close",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-close",
            },
            .{
                .name = "Reset",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "alloc", .member_type = "*ICommandAllocator" },
                    .{ .name = "initial_state", .member_type = "?*IPipelineState" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-reset",
            },
            .{
                .name = "ClearState",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "HRESULT",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "pso", .member_type = "?*IPipelineState" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-clearstate",
            },
            .{
                .name = "DrawInstanced",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "vertex_count_per_instance", .member_type = "UINT" },
                    .{ .name = "instance_count", .member_type = "UINT" },
                    .{ .name = "start_vertex_location", .member_type = "UINT" },
                    .{ .name = "start_instance_location", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-drawinstanced",
            },
            .{
                .name = "DrawIndexedInstanced",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "index_count_per_instance", .member_type = "UINT" },
                    .{ .name = "instance_count", .member_type = "UINT" },
                    .{ .name = "start_vertex_location", .member_type = "UINT" },
                    .{ .name = "base_vertex_location", .member_type = "UINT" },
                    .{ .name = "start_instance_location", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-drawindexedinstanced",
            },
            .{
                .name = "Dispatch",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "count_x", .member_type = "UINT" },
                    .{ .name = "count_y", .member_type = "UINT" },
                    .{ .name = "count_z", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-dispatch",
            },
            .{
                .name = "CopyBufferRegion",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst_buffer", .member_type = "*IResource" },
                    .{ .name = "dst_offset", .member_type = "UINT64" },
                    .{ .name = "src_buffer", .member_type = "*IResource" },
                    .{ .name = "src_offset", .member_type = "UINT64" },
                    .{ .name = "num_bytes", .member_type = "UINT64" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-copybufferregion",
            },
            .{
                .name = "CopyTextureRegion",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst", .member_type = "*const TEXTURE_COPY_LOCATION" },
                    .{ .name = "dst_x", .member_type = "UINT" },
                    .{ .name = "dst_y", .member_type = "UINT" },
                    .{ .name = "dst_z", .member_type = "UINT" },
                    .{ .name = "src", .member_type = "*const TEXTURE_COPY_LOCATION" },
                    .{ .name = "src_box", .member_type = "?*const BOX" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-copytextureregion",
            },
            .{
                .name = "CopyResource",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst", .member_type = "*IResource" },
                    .{ .name = "src", .member_type = "*IResource" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-copyresource",
            },
            .{
                .name = "CopyTiles",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "tiled_resource", .member_type = "*IResource" },
                    .{ .name = "tile_region_start_coordinate", .member_type = "*const TILED_RESOURCE_COORDINATE" },
                    .{ .name = "tile_region_size", .member_type = "*const TILE_REGION_SIZE" },
                    .{ .name = "buffer", .member_type = "*IResource" },
                    .{ .name = "buffer_start_offset_in_bytes", .member_type = "UINT64" },
                    .{ .name = "flags", .member_type = "TILE_COPY_FLAGS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-copytiles",
            },
            .{
                .name = "ResolveSubresource",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst_resource", .member_type = "*IResource" },
                    .{ .name = "dst_subresource", .member_type = "UINT" },
                    .{ .name = "src_resource", .member_type = "*IResource" },
                    .{ .name = "src_subresource", .member_type = "UINT" },
                    .{ .name = "format", .member_type = "dxgi.FORMAT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-resolvesubresource",
            },
            .{
                .name = "IASetPrimitiveTopology",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "topology", .member_type = "PRIMITIVE_TOPOLOGY" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-iasetprimitivetopology",
            },
            .{
                .name = "RSSetViewports",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "num", .member_type = "UINT" },
                    .{ .name = "viewports", .member_type = "[*]const VIEWPORT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-rssetviewports",
            },
            .{
                .name = "RSSetScissorRects",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "num", .member_type = "UINT" },
                    .{ .name = "rects", .member_type = "[*]const RECT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-rssetscissorrects",
            },
            .{
                .name = "OMSetBlendFactor",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "blend_factor", .member_type = "*const [4]FLOAT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-omsetblendfactor",
            },
            .{
                .name = "OMSetStencilRef",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "stencil_ref", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-omsetstencilref",
            },
            .{
                .name = "SetPipelineState",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "pso", .member_type = "*IPipelineState" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setpipelinestate",
            },
            .{
                .name = "ResourceBarrier",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "num", .member_type = "UINT" },
                    .{ .name = "barriers", .member_type = "[*]const RESOURCE_BARRIER" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-resourcebarrier",
            },
            .{
                .name = "ExecuteBundle",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "cmdlist", .member_type = "*IGraphicsCommandList" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-executebundle",
            },
            .{
                .name = "SetDescriptorHeaps",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "num", .member_type = "UINT" },
                    .{ .name = "heaps", .member_type = "[*]const *IDescriptorHeap" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setdescriptorheaps",
            },
            .{
                .name = "SetComputeRootSignature",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "root_signature", .member_type = "?*IRootSignature" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setcomputerootsignature",
            },
            .{
                .name = "SetGraphicsRootSignature",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "root_signature", .member_type = "?*IRootSignature" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setgraphicsrootsignature",
            },
            .{
                .name = "SetComputeRootDescriptorTable",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "root_index", .member_type = "UINT" },
                    .{ .name = "base_descriptor", .member_type = "GPU_DESCRIPTOR_HANDLE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setcomputerootdescriptortable",
            },
            .{
                .name = "SetGraphicsRootDescriptorTable",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "root_index", .member_type = "UINT" },
                    .{ .name = "base_descriptor", .member_type = "GPU_DESCRIPTOR_HANDLE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setgraphicsrootdescriptortable",
            },
            .{
                .name = "SetComputeRoot32BitConstant",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "index", .member_type = "UINT" },
                    .{ .name = "data", .member_type = "UINT" },
                    .{ .name = "off", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setcomputeroot32bitconstant",
            },
            .{
                .name = "SetGraphicsRoot32BitConstant",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "index", .member_type = "UINT" },
                    .{ .name = "data", .member_type = "UINT" },
                    .{ .name = "off", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setgraphicsroot32bitconstant",
            },
            .{
                .name = "SetComputeRoot32BitConstants",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "root_index", .member_type = "UINT" },
                    .{ .name = "num", .member_type = "UINT" },
                    .{ .name = "data", .member_type = "*const anyopaque" },
                    .{ .name = "offset", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setcomputeroot32bitconstants",
            },
            .{
                .name = "SetGraphicsRoot32BitConstants",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "root_index", .member_type = "UINT" },
                    .{ .name = "num", .member_type = "UINT" },
                    .{ .name = "data", .member_type = "*const anyopaque" },
                    .{ .name = "offset", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setgraphicsroot32bitconstants",
            },
            .{
                .name = "SetComputeRootConstantsBufferView",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "index", .member_type = "UINT" },
                    .{ .name = "buffer_location", .member_type = "GPU_VIRTUAL_ADDRESS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setcomputerootconstantbufferview",
            },
            .{
                .name = "SetGraphicsRootConstantsBufferView",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "index", .member_type = "UINT" },
                    .{ .name = "buffer_location", .member_type = "GPU_VIRTUAL_ADDRESS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setgraphicsrootconstantbufferview",
            },
            .{
                .name = "SetComputeRootShaderResourceView",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "index", .member_type = "UINT" },
                    .{ .name = "buffer_location", .member_type = "GPU_VIRTUAL_ADDRESS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setcomputerootshaderresourceview",
            },
            .{
                .name = "SetGraphicsRootShaderResourceView",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "index", .member_type = "UINT" },
                    .{ .name = "buffer_location", .member_type = "GPU_VIRTUAL_ADDRESS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setgraphicsrootshaderresourceview",
            },
            .{
                .name = "SetComputeRootUnorderedAccessView",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "index", .member_type = "UINT" },
                    .{ .name = "buffer_location", .member_type = "GPU_VIRTUAL_ADDRESS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setcomputerootunorderedaccessview",
            },
            .{
                .name = "SetGraphicsRootUnorderedAccessView",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "index", .member_type = "UINT" },
                    .{ .name = "buffer_location", .member_type = "GPU_VIRTUAL_ADDRESS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setgraphicsrootunorderedaccessview",
            },
            .{
                .name = "IASetVertexBuffers",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "start_slot", .member_type = "UINT" },
                    .{ .name = "num_views", .member_type = "UINT" },
                    .{ .name = "views", .member_type = "?[*]const VERTEX_BUFFER_VIEW" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-iasetvertexbuffers",
            },
            .{
                .name = "SOSetTargets",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "start_slot", .member_type = "UINT" },
                    .{ .name = "num_views", .member_type = "UINT" },
                    .{ .name = "views", .member_type = "?[*]const STREAM_OUTPUT_BUFFER_VIEW" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-sosettargets",
            },
            .{
                .name = "OMSetRenderTargets",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "num_rt_descriptors", .member_type = "UINT" },
                    .{ .name = "rt_descriptors", .member_type = "?[*]const CPU_DESCRIPTOR_HANDLE" },
                    .{ .name = "single_handle", .member_type = "BOOL" },
                    .{ .name = "ds_descriptors", .member_type = "?*const CPU_DESCRIPTOR_HANDLE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-omsetrendertargets",
            },
            .{
                .name = "ClearDepthStencilView",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "ds_view", .member_type = "CPU_DESCRIPTOR_HANDLE" },
                    .{ .name = "clear_flags", .member_type = "CLEAR_FLAGS" },
                    .{ .name = "depth", .member_type = "FLOAT" },
                    .{ .name = "stencil", .member_type = "UINT8" },
                    .{ .name = "num_rects", .member_type = "UINT" },
                    .{ .name = "rects", .member_type = "?[*]const RECT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-cleardepthstencilview",
            },
            .{
                .name = "ClearRenderTargetView",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "rt_view", .member_type = "CPU_DESCRIPTOR_HANDLE" },
                    .{ .name = "rgba", .member_type = "*const [4]FLOAT" },
                    .{ .name = "num_rects", .member_type = "UINT" },
                    .{ .name = "rects", .member_type = "?[*]const RECT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-clearrendertargetview",
            },
            .{
                .name = "ClearRenderTargetView",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "rt_view", .member_type = "CPU_DESCRIPTOR_HANDLE" },
                    .{ .name = "rgba", .member_type = "*const [4]FLOAT" },
                    .{ .name = "num_rects", .member_type = "UINT" },
                    .{ .name = "rects", .member_type = "?[*]const RECT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-clearrendertargetview",
            },
            .{
                .name = "ClearUnorderedAccessViewUint",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "gpu_view", .member_type = "GPU_DESCRIPTOR_HANDLE" },
                    .{ .name = "cpu_view", .member_type = "CPU_DESCRIPTOR_HANDLE" },
                    .{ .name = "resource", .member_type = "*IResource" },
                    .{ .name = "values", .member_type = "*const [4]UINT" },
                    .{ .name = "num_rects", .member_type = "UINT" },
                    .{ .name = "rects", .member_type = "?[*]const RECT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-clearunorderedaccessviewuint",
            },
            .{
                .name = "ClearUnorderedAccessViewFloat",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "gpu_view", .member_type = "GPU_DESCRIPTOR_HANDLE" },
                    .{ .name = "cpu_view", .member_type = "CPU_DESCRIPTOR_HANDLE" },
                    .{ .name = "resource", .member_type = "*IResource" },
                    .{ .name = "values", .member_type = "*const [4]FLOAT" },
                    .{ .name = "num_rects", .member_type = "UINT" },
                    .{ .name = "rects", .member_type = "?[*]const RECT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-clearunorderedaccessviewfloat",
            },
            .{
                .name = "DiscardResource",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "resource", .member_type = "*IResource" },
                    .{ .name = "region", .member_type = "?*const DISCARD_REGION" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-discardresource",
            },
            .{
                .name = "BeginQuery",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "query", .member_type = "*IQueryHeap" },
                    .{ .name = "query_type", .member_type = "QUERY_TYPE" },
                    .{ .name = "index", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-beginquery",
            },
            .{
                .name = "EndQuery",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "query", .member_type = "*IQueryHeap" },
                    .{ .name = "query_type", .member_type = "QUERY_TYPE" },
                    .{ .name = "index", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-endquery",
            },
            .{
                .name = "ResolveQueryData",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "query", .member_type = "*IQueryHeap" },
                    .{ .name = "query_type", .member_type = "QUERY_TYPE" },
                    .{ .name = "start_index", .member_type = "UINT" },
                    .{ .name = "num_queries", .member_type = "UINT" },
                    .{ .name = "dst_resource", .member_type = "*IResource" },
                    .{ .name = "buffer_offset", .member_type = "UINT64" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-resolvequerydata",
            },
            .{
                .name = "SetPredication",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "buffer", .member_type = "?*IResource" },
                    .{ .name = "buffer_offset", .member_type = "UINT64" },
                    .{ .name = "operation", .member_type = "PREDICATION_OP" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setpredication",
            },
            .{
                .name = "SetMarker",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "metadata", .member_type = "UINT" },
                    .{ .name = "data", .member_type = "?*const anyopaque" },
                    .{ .name = "size", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-setmarker",
            },
            .{
                .name = "BeginEvent",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "metadata", .member_type = "UINT" },
                    .{ .name = "data", .member_type = "?*const anyopaque" },
                    .{ .name = "size", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-beginevent",
            },
            .{
                .name = "EndEvent",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-endevent",
            },
            .{
                .name = "ExecuteIndirect",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "command_signature", .member_type = "*ICommandSignature" },
                    .{ .name = "max_command_count", .member_type = "UINT" },
                    .{ .name = "arg_buffer", .member_type = "*IResource" },
                    .{ .name = "arg_buffer_offset", .member_type = "UINT64" },
                    .{ .name = "count_buffer", .member_type = "*IResource" },
                    .{ .name = "count_buffer_offset", .member_type = "UINT64" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-executeindirect",
            },
        },
    },
    .IGraphicsCommandList1 = StructDefinition{
        .base = "dx12.IGraphicsCommandList",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "AtomicCopyBufferUINT",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst_buffer", .member_type = "*IResource" },
                    .{ .name = "dst_offset", .member_type = "UINT64" },
                    .{ .name = "src_buffer", .member_type = "*IResource" },
                    .{ .name = "src_offset", .member_type = "UINT64" },
                    .{ .name = "dependencies", .member_type = "UINT" },
                    .{ .name = "dependent_resources", .member_type = "[*]const *IResource" },
                    .{ .name = "dependent_subresource_ranges", .member_type = "[*]const SUBRESOURCE_RANGE_UINT64" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist1-atomiccopybufferuint",
            },
            .{
                .name = "AtomicCopyBufferUINT64",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst_buffer", .member_type = "*IResource" },
                    .{ .name = "dst_offset", .member_type = "UINT64" },
                    .{ .name = "src_buffer", .member_type = "*IResource" },
                    .{ .name = "src_offset", .member_type = "UINT64" },
                    .{ .name = "dependencies", .member_type = "UINT" },
                    .{ .name = "dependent_resources", .member_type = "[*]const *IResource" },
                    .{ .name = "dependent_subresource_ranges", .member_type = "[*]const SUBRESOURCE_RANGE_UINT64" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist1-atomiccopybufferuint64",
            },
            .{
                .name = "OMSetDepthBounds",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "min", .member_type = "FLOAT" },
                    .{ .name = "max", .member_type = "FLOAT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist1-omsetdepthbounds",
            },
            .{
                .name = "SetSamplePositions",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "num_samples", .member_type = "UINT" },
                    .{ .name = "num_pixels", .member_type = "UINT" },
                    .{ .name = "sample_positions", .member_type = "*SAMPLE_POSITION" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist1-setsamplepositions",
            },
            .{
                .name = "ResolveSubresourceRegion",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst_resource", .member_type = "*IResource" },
                    .{ .name = "dst_subresource", .member_type = "UINT" },
                    .{ .name = "dst_x", .member_type = "UINT" },
                    .{ .name = "dst_y", .member_type = "UINT" },
                    .{ .name = "src_resource", .member_type = "*IResource" },
                    .{ .name = "src_subresource", .member_type = "UINT" },
                    .{ .name = "src_rect", .member_type = "*RECT" },
                    .{ .name = "format", .member_type = "dxgi.FORMAT" },
                    .{ .name = "resolve_mode", .member_type = "RESOLVE_MODE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist1-resolvesubresourceregion",
            },
            .{
                .name = "SetViewInstanceMask",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "mask", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist1-setviewinstancemask",
            },
        },
    },
    .IGraphicsCommandList2 = StructDefinition{
        .base = "dx12.IGraphicsCommandList1",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "WriteBufferImmediate",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "count", .member_type = "UINT" },
                    .{ .name = "params", .member_type = "[*]const WRITEBUFFERIMMEDIATE_PARAMETER" },
                    .{ .name = "modes", .member_type = "?[*]const WRITEBUFFERIMMEDIATE_MODE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist2-writebufferimmediate",
            },
        },
    },
    .IGraphicsCommandList3 = StructDefinition{
        .base = "dx12.IGraphicsCommandList2",
        .is_extern = true,
        .methods = &.{.{
            .name = "SetProtectedResourceSession",
            .call_conv = "winapi",
            .namespace = null,
            .method_type = .Default,
            .return_type = "void",
            .params = &.{
                .{ .name = "self", .member_type = "*@This()" },
                .{ .name = "prsession", .member_type = "?*IProtectedResourceSession" },
            },
            .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist3-setprotectedresourcesession",
        }},
    },
    .IGraphicsCommandList4 = StructDefinition{
        .base = "dx12.IGraphicsCommandList3",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "BeginRenderPass",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "num_render_targets", .member_type = "UINT" },
                    .{ .name = "render_targets", .member_type = "?[*]const RENDER_PASS_RENDER_TARGET_DESC" },
                    .{ .name = "depth_stencil", .member_type = "?*const RENDER_PASS_DEPTH_STENCIL_DESC" },
                    .{ .name = "flags", .member_type = "RENDER_PASS_FLAGS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-beginrenderpass",
            },
            .{
                .name = "EndRenderPass",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-endrenderpass",
            },
            .{
                .name = "InitializeMetaCommand",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "meta_cmd", .member_type = "*IMetaCommand" },
                    .{ .name = "init_param_data", .member_type = "?*const anyopaque" },
                    .{ .name = "data_size", .member_type = "SIZE_T" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-initializemetacommand",
            },
            .{
                .name = "ExecuteMetaCommand",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "meta_cmd", .member_type = "*IMetaCommand" },
                    .{ .name = "exe_param_data", .member_type = "?*const anyopaque" },
                    .{ .name = "data_size", .member_type = "SIZE_T" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-executemetacommand",
            },
            .{
                .name = "BuildRaytracingAccelerationStructure",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "desc", .member_type = "*const BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC" },
                    .{ .name = "num_post_build_descs", .member_type = "UINT" },
                    .{ .name = "post_build_descs", .member_type = "?[*]const RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_DESC" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-buildraytracingaccelerationstructure",
            },
            .{
                .name = "EmitRaytracingAccelerationStructurePostbuildInfo",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "desc", .member_type = "*const RAYTRACING_ACCELERATION_STRUCTURE_POSTHBUILD_INFO_DESC" },
                    .{ .name = "num_src_accel_structs", .member_type = "UINT" },
                    .{ .name = "src_accel_struct_data", .member_type = "[*]const GPU_VIRTUAL_ADDRESS" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-emitraytracingaccelerationstructurepostbuildinfo",
            },
            .{
                .name = "CopyRaytracingAccelerationStructure",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "dst_data", .member_type = "GPU_VIRTUAL_ADDRESS" },
                    .{ .name = "src_data", .member_type = "GPU_VIRTUAL_ADDRESS" },
                    .{ .name = "mode", .member_type = "RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-copyraytracingaccelerationstructure",
            },
            .{
                .name = "SetPipelineState1",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "state_obj", .member_type = "*IStateObject" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-setpipelinestate1",
            },
            .{
                .name = "DispatchRays",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "desc", .member_type = "*const DISPATCH_RAYS_DESC" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist4-dispatchrays",
            },
        },
    },
    .IGraphicsCommandList5 = StructDefinition{
        .base = "dx12.IGraphicsCommandList4",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "RSSetShadingRate",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "base_shading_rate", .member_type = "SHADING_RATE" },
                    .{ .name = "combiners", .member_type = "?*const [RS_SET_SHADING_RATE_COMBINER_COUNT]SHADING_RATE_COMBINER" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist5-rssetshadingrate",
            },
            .{
                .name = "RSSetShadingRateImage",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "shading_rate_img", .member_type = "?*IResource" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist5-rssetshadingrateimage",
            },
        },
    },
    .IGraphicsCommandList6 = StructDefinition{
        .base = "dx12.IGraphicsCommandList5",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "DispatchMesh",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "thread_group_count_x", .member_type = "UINT" },
                    .{ .name = "thread_group_count_y", .member_type = "UINT" },
                    .{ .name = "thread_group_count_z", .member_type = "UINT" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist6-dispatchmesh",
            },
        },
    },
    .IGraphicsCommandList7 = StructDefinition{
        .base = "dx12.IGraphicsCommandList6",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "Barrier",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "num_barrier_groups", .member_type = "UINT32" },
                    .{ .name = "barrier_groups", .member_type = "[*]const BARRIER_GROUP" },
                },
                .doc = "https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist7-barrier",
            },
        },
    },
    .IGraphicsCommandList8 = StructDefinition{
        .base = "dx12.IGraphicsCommandList7",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "OMSetFrontAndBackStencilRef",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "front_stencil_ref", .member_type = "UINT" },
                    .{ .name = "back_stencil_ref", .member_type = "UINT" },
                },
                .doc = "TBD",
            },
        },
    },
    .IGraphicsCommandList9 = StructDefinition{
        .base = "dx12.IGraphicsCommandList8",
        .is_extern = true,
        .methods = &.{
            .{
                .name = "RSSetDepthBias",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "depth_bias", .member_type = "FLOAT" },
                    .{ .name = "depth_bias_clamp", .member_type = "FLOAT" },
                    .{ .name = "slope_scaled_depth_bias", .member_type = "FLOAT" },
                },
                .doc = "TBD",
            },
            .{
                .name = "IASetIndexBufferStripCutValue",
                .call_conv = "winapi",
                .namespace = null,
                .method_type = .Default,
                .return_type = "void",
                .params = &.{
                    .{ .name = "self", .member_type = "*@This()" },
                    .{ .name = "cut_value", .member_type = "INDEX_BUFFER_STRIP_CUT_VALUE" },
                },
                .doc = "TBD",
            },
        },
    },
};
